# Generated by Django 6.0.6 on 2026-06-17 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('release_date', models.DateField(verbose_name='Дата создания')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5')], verbose_name='Рейтинг')),
            ],
        ),
    ]
